import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatTabsModule,
    MatFormFieldModule,
    MatOptionModule,
    MatSelectModule,
    MatTableDataSource,
    MatTableModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatInputModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatGridListModule,
    MatPaginatorModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatBadgeModule,
    MatStepperModule,
    MatSnackBarModule,
    MatSortModule
  } from '@angular/material';

  @NgModule({
    imports: [
      MatButtonModule,
      MatMenuModule,
      MatToolbarModule,
      MatIconModule,
      MatCardModule,
      MatTabsModule,
      MatFormFieldModule,
      MatOptionModule,
      MatSelectModule,
      MatTableModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatInputModule,
      MatCheckboxModule,
      MatSidenavModule,
      MatGridListModule,
      MatPaginatorModule,
      MatAutocompleteModule,
      MatDialogModule,
      MatBadgeModule,
      MatStepperModule,
      MatSnackBarModule,
      MatSortModule
    ],
    exports: [
      MatButtonModule,
      MatMenuModule,
      MatToolbarModule,
      MatIconModule,
      MatCardModule,
      MatTabsModule,
      MatFormFieldModule,
      MatOptionModule,
      MatSelectModule,
      MatTableModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatInputModule,
      MatCheckboxModule,
      MatSidenavModule,
      MatGridListModule,
      MatPaginatorModule,
      MatAutocompleteModule,
      MatDialogModule,
      MatBadgeModule,
      MatStepperModule,
      MatSnackBarModule,
      MatSortModule
    ]
  })
  export class MaterialModule {}
